export const TAG_COLLECTION: string[] = [
  "Action",
  "Adventure",
  "Aliens",
  "Alternate Universe",
  "Anti-Hero",
  "Arranged Marriage",
  "Artificial Intelligence",
  "Assassins",
  "Augmented Reality",
  "Boarding School",
  "Body Swapping",
  "Boxing",
  "Boys' Love",
  "Bullying",
  "Class Struggle",
  "College",
  "Coming of Age",
  "Conspiracy",
  "Crime",
  "Criminal Organization",
  "Cult",
  "Cultivation",
  "Curses",
  "Cyberpunk",
  "Cyborg",
  "Death Game",
  "Demons",
  "Detective",
  "Dragons",
  "Dungeon",
  "Dystopian",
  "E-Sports",
  "Elderly Protagonist",
  "Elf",
  "Ensemble Cast",
  "Environmental",
  "Espionage",
  "Exorcism",
  "Fairy",
  "Fake Relationship",
  "Family Life",
  "Female Harem",
  "Female Protagonist",
  "Fitness",
  "Food",
  "Football",
  "Full Color",
  "Gambling",
  "Gender Bending",
  "Ghost",
  "Gods",
  "Guns",
  "Historical",
  "Hospital",
  "Isekai",
  "Kaiju",
  "Kingdom Management",
  "Long Strip",
  "Love Triangle",
  "Mafia",
  "Magic",
  "Maids",
  "Makeup",
  "Male Harem",
  "Male Protagonist",
  "Marriage",
  "Martial Arts",
  "Medicine",
  "Medieval",
  "Memory Manipulation",
  "Military",
  "Mixed Gender Harem",
  "Monster Boy",
  "Monster Girl",
  "Mythology",
  "Ninja",
  "Office",
  "Orphan",
  "Parenthood",
  "Parody",
  "Photography",
  "Pirates",
  "Police",
  "Politics",
  "Post-Apocalyptic",
  "Primarily Female Cast",
  "Primarily Male Cast",
  "Prison",
  "Psychological",
  "Reincarnation",
  "Religion",
  "Revenge",
  "Robots",
  "Royal Affairs",
  "School",
  "School Club",
  "Shapeshifting",
  "Skateboarding",
  "Slapstick",
  "Space",
  "Steampunk",
  "Super Power",
  "Superhero",
  "Survival",
  "Swordplay",
  "Teacher",
  "Teens' Love",
  "Thriller",
  "Time Manipulation",
  "Tragedy",
  "Travel",
  "Unrequited Love",
  "Urban Fantasy",
  "Vampire",
  "Video Games",
  "Villainess",
  "Virtual World",
  "War",
  "Writing",
  "Yandere",
] as const;
export type Tag = (typeof TAG_COLLECTION)[number];
