export const TAG_COLLECTION: string[] = [
  "Action",
  "Adventure",
  "Age Gap",
  "Aliens",
  "Alternate Universe",
  "Amnesia",
  "Angels",
  "Animals",
  "Anti-Hero",
  "Arranged Marriage",
  "Artificial Intelligence",
  "Assassins",
  "Augmented Reality",
  "Band",
  "Baseball",
  "Basketball",
  "Battle Royale",
  "Biographical",
  "Boarding School",
  "Body Swapping",
  "Boxing",
  "Boys' Love",
  "Bullying",
  "Camping",
  "Card Battle",
  "Cars",
  "Chuunibyou",
  "Circus",
  "Class Struggle",
  "Clone",
  "Cohabitation",
  "College",
  "Coming of Age",
  "Conspiracy",
  "Crime",
  "Criminal Organization",
  "Crossdressing",
  "Cult",
  "Cultivation",
  "Curses",
  "Cute Boys Doing Cute Things",
  "Cute Girls Doing Cute Things",
  "Cyberpunk",
  "Cyborg",
  "Dancing",
  "Death Game",
  "Delinquents",
  "Demons",
  "Detective",
  "Dinosaurs",
  "Disability",
  "Dissociative Identities",
  "Dragons",
  "Dungeon",
  "Dystopian",
  "E-Sports",
  "Elderly Protagonist",
  "Elf",
  "Ensemble Cast",
  "Environmental",
  "Espionage",
  "Exorcism",
  "Fairy",
  "Fake Relationship",
  "Family Life",
  "Female Harem",
  "Female Protagonist",
  "Fencing",
  "Firefighters",
  "Fitness",
  "Food",
  "Football",
  "Found Family",
  "Full Color",
  "Gambling",
  "Gangs",
  "Gender Bending",
  "Ghost",
  "Gods",
  "Guns",
  "Henshin",
  "Heterosexual",
  "Hikikomori",
  "Historical",
  "Hospital",
  "Isekai",
  "Iyashikei",
  "Judo",
  "Kaiju",
  "Kemonomimi",
  "Kids",
  "Kingdom Management",
  "Long Strip",
  "Love Triangle",
  "Mafia",
  "Magic",
  "Maids",
  "Makeup",
  "Male Harem",
  "Male Protagonist",
  "Marriage",
  "Martial Arts",
  "Medicine",
  "Medieval",
  "Memory Manipulation",
  "Mermaid",
  "Military",
  "Mixed Gender Harem",
  "Monster Boy",
  "Monster Girl",
  "Motorcycles",
  "Mountaineering",
  "Music",
  "Mythology",
  "Ninja",
  "Noir",
  "Office",
  "Orphan",
  "Otaku Culture",
  "Parenthood",
  "Parkour",
  "Parody",
  "Photography",
  "Pirates",
  "Police",
  "Politics",
  "Post-Apocalyptic",
  "Pregnancy",
  "Primarily Female Cast",
  "Primarily Male Cast",
  "Prison",
  "Psychological",
  "Reincarnation",
  "Religion",
  "Revenge",
  "Robots",
  "Royal Affairs",
  "Sadism",
  "Samurai",
  "Satire",
  "School",
  "School Club",
  "Shapeshifting",
  "Shoujo",
  "Shounen",
  "Skateboarding",
  "Slapstick",
  "Space",
  "Steampunk",
  "Succubus",
  "Super Power",
  "Superhero",
  "Survival",
  "Swordplay",
  "Teacher",
  "Teens' Love",
  "Thriller",
  "Time Manipulation",
  "Tomboy",
  "Tragedy",
  "Transgender",
  "Travel",
  "Tsundere",
  "Unrequited Love",
  "Urban Fantasy",
  "Vampire",
  "Video Games",
  "Villainess",
  "Virtual World",
  "War",
  "Werewolf",
  "Witch",
  "Work",
  "Writing",
  "Yakuza",
  "Yandere",
  "Yuri",
  "Zombie",
] as const;
export type Tag = (typeof TAG_COLLECTION)[number];
